### ISSUE TITLE
Language!

### ISSUE THREAD

**Issue by devFallingstar** [BlueCat-Community/Android_Architecture_Study#1]
Sorry, I mean a "language".
What should we use? English( as we always did ;D ) or Korean?

**Comment by rurimo** [comment]
@devFallingstar 
The basic language for writing `README`, `commit messages` and `code comments` should be English.
However, it is okay to use Korean to communicate with each other like what `issues title`, `issue-comments`, and `code-reviews`'.

**Comment by devFallingstar** [comment]
@rurimo 
Great, thanks. 👍
